# syntax=docker/dockerfile:1
FROM ubuntu:22.04

# Install required packages
RUN apt-get update && apt-get install -y --no-install-recommends  \
    python3.10 python3-pip  \
    xz-utils \
    wget \
    unzip \
    libgl1 \
    libglib2.0-0 ffmpeg \
    && rm -rf /var/lib/apt/lists/*


WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY *.py ./
COPY streamonitor ./streamonitor

EXPOSE 6969
CMD [ "python3", "Downloader.py"]